### ISSUE TITLE
png2tga  rgba image  color distortion

### ISSUE THREAD

**Issue by lichspace** [lunapaint/tga-codec#6]
<img width="1505" alt="image" src="https://github.com/lunapaint/tga-codec/assets/5037114/e021cb9d-a44e-4ab4-a940-c80c5191e6ab">

`
const { encodeTga } = require('@tencent/tga-encode')
const { decodePng } = require('@lunapaint/png-codec')
const { readFile, writeFile } = require('fs/promises')

const fetchPng2tag = async (url, dist) => {
  const data = await readFile(url);
  const decoded = await decodePng(new Uint8Array(data), { force32: true });
  const encoded = await encodeTga(decoded.image, { imageType: 2 });
  await writeFile(dist, encoded.data);
};

fetchPng2tag('./assets/rgba.png', __dirname + '/test/test.tga')
`

**Comment by Tyriar** [comment]
To fix something like this I'll need a file to test against. Also encodeTga seems to come from `@tencent/tga-encode` which isn't public?
